<?php
/**
 * Unique, single-use coupons for emails.
 *
 * @package CheckoutFlow
 */

namespace CheckoutFlow\Mail;

defined( 'ABSPATH' ) || exit;

class Coupons {

	/**
	 * @param string $email    Customer email the coupon is locked to.
	 * @param array  $block    Coupon block props (discount_type, amount, days, free_shipping).
	 * @param int    $queue_id Queue row, for reference.
	 * @return array { code, amount, expiry }
	 */
	public static function create( $email, $block, $queue_id = 0 ) {
		$type   = 'fixed_cart' === $block['discount_type'] ? 'fixed_cart' : 'percent';
		$amount = max( 0, (float) $block['amount'] );
		$days   = max( 1, (int) $block['days'] );

		do {
			$code = strtolower( 'cf' . wp_generate_password( 8, false, false ) );
		} while ( wc_get_coupon_id_by_code( $code ) );

		$expires = new \WC_DateTime( '+' . $days . ' days' );
		$coupon  = new \WC_Coupon();
		$coupon->set_code( $code );
		$coupon->set_discount_type( $type );
		$coupon->set_amount( $amount );
		$coupon->set_individual_use( true );
		$coupon->set_usage_limit( 1 );
		$coupon->set_usage_limit_per_user( 1 );
		$coupon->set_email_restrictions( array( $email ) );
		$coupon->set_date_expires( $expires );
		$coupon->set_free_shipping( ! empty( $block['free_shipping'] ) );
		/* translators: %d: queue id */
		$coupon->set_description( sprintf( __( 'Generated by CheckoutFlow for email #%d', 'checkoutflow' ), $queue_id ) );
		$coupon->update_meta_data( '_cf_generated', 1 );
		$coupon->save();

		return array(
			'code'   => $code,
			'amount' => self::format_amount( $type, $amount ),
			'expiry' => wc_format_datetime( $expires ),
		);
	}

	public static function format_amount( $type, $amount ) {
		return 'percent' === $type
			? wc_format_localized_decimal( $amount ) . '%'
			: html_entity_decode( wp_strip_all_tags( wc_price( $amount ) ), ENT_QUOTES, 'UTF-8' );
	}

	/**
	 * Preview placeholder.
	 */
	public static function sample( $block ) {
		return array(
			'code'   => 'CFSAMPLE',
			'amount' => self::format_amount( $block['discount_type'], (float) $block['amount'] ),
			'expiry' => wc_format_datetime( new \WC_DateTime( '+' . max( 1, (int) $block['days'] ) . ' days' ) ),
		);
	}

	/**
	 * Delete generated coupons that expired more than a week ago and were never used.
	 */
	public static function cleanup() {
		$ids = get_posts(
			array(
				'post_type'      => 'shop_coupon',
				'post_status'    => 'any',
				'fields'         => 'ids',
				'posts_per_page' => 200,
				'meta_query'     => array( // phpcs:ignore WordPress.DB.SlowDBQuery
					array( 'key' => '_cf_generated', 'value' => 1 ),
					array( 'key' => 'usage_count', 'value' => 0 ),
					array( 'key' => 'date_expires', 'value' => time() - WEEK_IN_SECONDS, 'compare' => '<', 'type' => 'NUMERIC' ),
				),
			)
		);
		foreach ( $ids as $id ) {
			wp_delete_post( $id, true );
		}
	}
}
